# Generated by Django 3.2.14 on 2022-07-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
